[workspace]
resolver = "3"
members = [
    "crates/01-first-world",
    "crates/02-console-log",
    "crates/03-without-a-bundler",
    "crates/04-synchronous-instantiation"

, "crates/04-synchronous-instantiation", "crates/05-import-js"]
[workspace.dependencies]
wasm-bindgen = "0.2.100"


