[package]
name = "closures"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = {workspace = true}
js-sys = {workspace = true}
web-sys = {workspace = true,features = ["Document","Element","HtmlElement","Window","CssStyleDeclaration"]}
[lib]
crate-type = ["cdylib"]