[package]
name = "dom"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = {workspace = true}
web-sys = {workspace = true,features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window']}

[lib]
crate-type = ["cdylib"]