[package]
name = "performance"
version = "0.1.0"
edition = "2024"

[dependencies]
humantime="2.2.0"
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = ['Window', 'Performance', 'PerformanceTiming'] }

[lib]
crate-type = ["cdylib"]