name: build
on:
    workflow_dispatch:
        inputs:
        version:
            description: 'Version to build'
            required: true
            default: 'latest'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 读取仓库
        uses: actions/checkout@v4
      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 安装rust
        uses: actions-rs/toolchain@v1
      - name: 安装cargo
        uses: actions-rs/cargo@v1
      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install
